version: '2'
services:
  svn:
    restart: always
    build:
      context: ./svn/build
    image: svn-server
    container_name: svn-server
    hostname: svn-server
    volumes_from: 
      - svn-data
    ports:
      - 81:80
  nexus:
    restart: always
    image: sonatype/nexus3
    container_name: nexus3-server
    hostname: nexus3-server
#    volumes_from:
#      - nexus3-data
    ports:
      - 8081:8081  
  jenkins:
    restart: always
    image: jenkinsci/jenkins
    container_name: jenkins-server
    hostname: jenkins-server
    depends_on:
      - svn
    volumes_from: 
      - jenkins-data
    ports:
      - 8080:8080 
      - 50000:50000
  sonar:
    restart: always
    image: sonarqube
    container_name: sonar-server
    hostname: sonar-server
    depends_on:
      - sonar-db
    volumes_from:
    - sonar-plugins-data
    ports:
      - 9000:9000
      - 9092:9092
    environment:
       - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
  sonar-db:
    image: postgres
    container_name: sonar-db
    hostname: sonar-db
    volumes_from:
      - sonar-db-data
    environment:
     - POSTGRES_USER=sonar
     - POSTGRES_PASSWORD=sonar

# -------------
# storage
# -------------
  svn-data:
    image: svn-server
    volumes:
      - /opt/svn/
    command: /bin/true
  nexus3-data:
    image: sonatype/nexus3
    command: /bin/true
  jenkins-data:
    image: jenkinsci/jenkins
    volumes:
      - /var/jenkins_home
    command: /bin/true
    #chown 1000 /var/jenkins_home
  sonar-plugins-data:
    image: sonarqube
    volumes:
     - /opt/sonarqube/extensions
     - /opt/sonarqube/lib/bundled-plugins
    command: /bin/true
  sonar-db-data:
    image: postgres
    volumes:
      - /var/lib/postgresql
    command: /bin/true


