version: '2'
services:
  svn:
    extends:
      file: ./svn/docker-compose-svn.yml
      service: svn
#  sonar:
#    restart: always
#    image: sonarqube
#    container_name: sonar_server
#    extra_hosts:
#     - "docker.iata.org:192.169.4.240"
#    hostname: sonar-server
#    depends_on:
#      - db
#    ports:
#      - 9000:9000
#      - 9092:9092
#    environment:
#       - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
#  db:
#    image: postgres
#    container_name: sonar_postgres_db
#    hostname: sonar-postgres-db
#    volumes_from:
#      - datadb
#    environment:
#     - POSTGRES_USER=sonar
#     - POSTGRES_PASSWORD=sonar

#  datadb:
#    image: alpine
#    volumes:
#      - ./data/postgresql:/var/lib/postgresql
#    command: /bin/true

#  plugins:
#    image: alpine
#    volumes:
#     - ./data/sonarqube/extensions:/opt/sonarqube/extensions
#     - ./data/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
#    command: /bin/true


